spring:
  application:
    name: ChatApp

  datasource:
    url: jdbc:postgresql://localhost:5432/convoDb?options=-c%20TimeZone=UTC
    username: postgresUser
    password: Postgres@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates tables based on your Java classes
    show-sql: true      # Prints SQL queries to the console (useful for debugging)
    properties:
      hibernate:
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect